Forum-Mind/urls.py
#Import Dependencies
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url,include
from users import views as user_views
from django.conf.urls.static import static
from users import views as user_views
from django.conf import settings

#URL Patterns
urlpatterns = [
	#/admin/
    path('admin/', admin.site.urls),
    #/
    path('',include('homepage.urls'),name='home'),
    #/news/
    path('news/',include('news.urls'),name='news'),
    #/jobs/
    path('jobs/',include('jobs.urls'),name='job'),
    #/forums/
    path('forums/',include('forums.urls'),name='forum'),
    #/community/
    path('community/',include('hub.urls'),name='community'),
    #/register/
    path('register/',user_views.register,name='register'),
    #/login/
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    #/logout/
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    #/profile/
    path('profile/',user_views.profile,name='profile'),
    #/profile/accomplishments/
    path('profile/accomplishments/',user_views.accomplishments,name='profacc'),
    #/profile/edit/
    path('profile/edit/',user_views.edit,name='profile-edit'),
    #/profile/applications/
    path('profile/applications/',user_views.applications,name='applications'),
    #/profile/offers/
    path('profile/offers/',user_views.offers,name='joboffers'),
    #/profile/candidates/
    path('profile/candidates/',user_views.candidates,name='jobcandidates'),
    #/profile/converstaions/
    path('profile/converstaions/',user_views.user_conversations,name='jobconv'),
    #/profile/github/<username>/
    path('profile/github/<str:username>',user_views.github,name='profgit'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hub/urls.py
#Import Dependencies
from django.urls import path
from django.conf.urls import url,include
from . import views
from .views import (
	PostListView,
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserPostListView
	)

#URL Patterns
urlpatterns = [
	#/community/
	path('',PostListView.as_view(),name='network'),
	#/community/new/
	path('new/',PostCreateView.as_view(),name='network-create'),
	#/community/<pk>
	path('<int:pk>/',PostDetailView.as_view(),name='network-post'),
	#/community/<pk>/update/
	path('<int:pk>/update/',PostUpdateView.as_view(),name='network-update'),
	#/community/<pk>/delete/
	path('<int:pk>/delete/',PostDeleteView.as_view(),name='network-delete'),
	#/community/user/<username>
	path('user/<str:username>',UserPostListView.as_view(),name='user-posts'),	
]

jobs/urls.py
#Import Dependencies
from django.conf.urls import url
from . import views

#App Name
app_name = 'jobs'

#URL Patterns
urlpatterns = [
    #/jobs/
    url(r'^$', views.index, name='index'),

    #/jobs/offers/
    url(r'^offers/$', views.job_offers, name='job_offers'),

    #/jobs/offers/<offerid>/
    url(r'offers/(?P<offer_id>[0-9]+)/$', views.offer_detail, name='offer_detail'),    

    #/jobs/offers/<offer_id>/apply/
    url(r'offers/(?P<offer_id>[0-9]+)/apply/$', views.job_apply, name='job_apply'),

    #/jobs/offers/<offerid>/add/
    url(r'offers/add/$', views.job_offer_add, name='job_offer_add'),    

    #/jobs/offers/<id>/delete/
    url(r'offers/(?P<offer_id>[0-9]+)/delete/$', views.offer_delete, name='offer_delete'),

    #/jobs/offers/update/
    url(r'offers/(?P<offer_id>[0-9]+)/update/$', views.offer_update, name='offer_update'),

    #/jobs/applications/<id>
    url(r'applications/(?P<application_id>[0-9]+)/$', views.application_detail, name='application_detail'),

    #/jobs/applications/<id>/create_conversation/
    url(r'applications/(?P<application_id>[0-9]+)/create_conversation/$', views.create_conversation, name='create_conversation'),

    #/jobs/search/
    url(r'search/$', views.search, name='search'),
    
    #/jobs/messages/<id>/delete/
    url(r'^messages/(?P<conversation_id>[0-9]+)/delete$', views.conversation_delete, name='conversation_delete'),
    
    #/jobs/messages/<id>/
    url(r'^messages/(?P<conversation_id>[0-9]+)/$', views.conversation, name='conversation'),
    
    #/jobs/users/<name>/
    url(r'^users/(?P<username>\w+)/$', views.user_profile, name='user_profile'),

    #/jobs/users/<name>/applications/
    url(r'^users/(?P<username>\w+)/applications', views.user_applications, name='user_applications'),
    
    #/jobs/users/<name>/offers/
    url(r'^users/(?P<username>\w+)/offers', views.user_offers, name='user_offers'),

    #/jobs/users/<name>/candidates/
    url(r'^users/(?P<username>\w+)/candidates', views.candidates, name='candidates'),       

    #/jobs/users/<name>/conversations/
    url(r'^users/(?P<username>\w+)/conversations/$', views.user_conversations, name='user_conversations'),
]

users/models.py
#Import Dependencies
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

#Class for Profile Table
class Profile(models.Model):
	user = models.OneToOneField(User,on_delete = models.CASCADE)
	image = models.ImageField(default='default.jpg',upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self,**kwargs):
		super().save()
		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300,300)
			img.thumbnail(output_size)
			img.save(self.image.path)

users/forms.py
#Import Dependencies
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

#Forms

#Form for user registration
class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)

	class Meta:
		model = User
		fields = ['username','first_name','last_name','email','password1','password2']

#Form for updating user information - [user,email]
class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ['username','email']

#Form for updating user information - [image]
class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['image']

users/views.py
#Import Dependencies
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm
from jobs.models import JobApplication, JobOffer, Conversation
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from hub.models import Accomplishment
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import (ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
    )
from django.template import loader
from django.http import HttpResponse
import requests

# Create your views here.

#View function for register
def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request,f'Account created for {username}! You can now login :)')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request,'users/register.html',{'form':form})

#View function for profile
@login_required
def profile(request):
	context = {
	}
	return render(request,'users/profile.html',context)

#View function for editing the profile
@login_required
def edit(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST,instance=request.user)
		p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)

		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request,f'Your Account has been updated!')
			return redirect('profile')			

	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)

	context = {
	'u_form' : u_form,
	'p_form' : p_form
	}
	return render(request,'users/profile-edit.html',context)

#View function for applications
@login_required
def applications(request):
    applications = []
    title = 'Your Applications'
    if request.user.is_authenticated:
        applications = JobApplication.objects.filter(user=request.user).order_by('-created_date')

    paginator = Paginator(applications, 10)
    page = request.GET.get('page')

    try:
        applications = paginator.page(page)
    except PageNotAnInteger:
        applications = paginator.page(1)
    except EmptyPage:
        applications = paginator.page(paginator.num_pages)

    context = {
        'applications': applications,
        'title': title,
    }
    return render(request, 'users/user_applications.html', context)

#View function for offers
@login_required
def offers(request):
    offers = []
    if request.user.is_authenticated:
        offers = JobOffer.objects.filter(user=request.user).order_by('-created_date')
        paginator = Paginator(offers, 10)
        page = request.GET.get('page')

        try:
            offers = paginator.page(page)
        except PageNotAnInteger:
            offers = paginator.page(1)
        except EmptyPage:
            offers = paginator.page(paginator.num_pages)

    return render(request, 'users/useroffers.html', {'offers': offers})

#View function for candidates
@login_required
def candidates(request):
    applications = []
    title = 'Your Candidates'
    if request.user.is_authenticated:
        applications = JobApplication.objects.filter(job_offer__user=request.user).order_by('-created_date')

    paginator = Paginator(applications, 10)
    page = request.GET.get('page')

    try:
        applications = paginator.page(page)
    except PageNotAnInteger:
        applications = paginator.page(1)
    except EmptyPage:
        applications = paginator.page(paginator.num_pages)

    context = {
        'applications': applications,
        'title': title,
    }
    return render(request, 'users/candidates.html', context)

#View function for user conversations
@login_required
def user_conversations(request):
    if request.user.is_authenticated:
        conversations = Conversation.objects.filter(
            Q(user_one=request.user) |
            Q(user_two=request.user)
        )
        context = {
            'conversations': conversations,
        }
        return render(request, 'users/user_conversations.html', context)

#View function for accomplishments
@login_required
def accomplishments(request):
    accomplishments = []
    if request.user.is_authenticated:
        accomplishments = Accomplishment.objects.filter(author=request.user)
        context = {
            'accomplishments':accomplishments,
        }
        return render(request,'users/accomplishments.html',context)

#View function for github repositories
@login_required
def github(request,username):
    #user = get_object_or_404(User,username=self.kwargs.get('username'))
    req = requests.get('https://api.github.com/users/'+username+'/repos?per_page=1000')
    json = req.json()
    lis = []
    for i in range(0,len(json)):
        #print("Project Number:",i+1)
        #print("Project Name:",json[i]['name'])
        #print("Project URL:",json[i]['svn_url'],"\n")
        git = {'number': str(i+1), 'name': str(json[i]['name']), 'url': str(json[i]['svn_url'])}
        lis.append(git)
    context = {
        'git' : lis
    }
    template = loader.get_template('users/github.html')
    return HttpResponse(template.render(context,request))

users/templates/users/candidates.html
<html>
    <head>
        <title>Forum-Mind Profile </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href='https://fonts.googleapis.com/css?family=RobotoDraft' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><style>
    html,body,h1,h2,h3,h4,h5 {font-family: "RobotoDraft", "Roboto", sans-serif;}
    .w3-bar-block .w3-bar-item{padding:16px}
    </style>
    </head>
{% extends 'hub/navbar.html' %}
{% load static %}
{% block body %}

<nav class="w3-sidebar w3-bar-block w3-collapse w3-white w3-animate-left w3-card" style="z-index:3;width:320px;" id="mySidebar">
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-border-bottom w3-large"><h2><b>Forum-Mind</b></h2></a>
  <a href="javascript:void(0)" onclick="w3_close()" title="Close Sidemenu" 
  class="w3-bar-item w3-button w3-hide-large w3-large">Close <i class="fa fa-remove"></i></a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-star"></i> My Profile</a>
  <a href="{% url 'profacc' %}" class="w3-bar-item w3-button"><i class="fa fa-trophy"></i> My Accomplishments</a>
  <a href="/profile/github/{{user.username}}" class="w3-bar-item w3-button"><i class="fa fa-github-alt"></i>
  </i> Github Activity</a>
  <a href="{% url 'profile-edit' %}" class="w3-bar-item w3-button"><i class="fa fa-pencil"></i> Edit Profile</a>
  
  <a href="{% url 'applications' %}" class="w3-bar-item w3-button"><i class="fa fa-hourglass-end w3-margin-right"></i>My Applications</a>
  <a href="{% url 'joboffers' %}" class="w3-bar-item w3-button"><i class="fa fa-paper-plane w3-margin-right"></i>My Offers</a>
  <a href="{% url 'jobcandidates' %}" class="w3-bar-item w3-button"  style="background-color:#D3D3D3"><i class="fa fa-user w3-margin-right"></i>
Candidates</a>
  <a href="{% url 'jobconv' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope w3-margin-right"></i>
Messages</a>
</nav>


<!-- Overlay effect when opening the side navigation on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="Close Sidemenu" id="myOverlay"></div>

<script>

  function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
  }

  function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
  }
</script>

<script>
  var openTab = document.getElementById("firstTab");
  openTab.click();
</script>



<!-- Page content -->
<br/><br/><p></p>
{% if applications %}
    <div class="row">
        <div class="col-sm-8 col-lg-9" style="text-align: center;">
            <div class="pagination">
                <span class="step-links">
                    {% if applications.has_previous %}
                    <a href="?page={{ applications.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ applications.number }} of {{ applications.paginator.num_pages }}.
                    </span>

                    {% if applications.has_next %}
                        <a href="?page={{ applications.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
      </div>
    </div>
{% endif %}
<br/><br/><p></p>
{% if request.user.is_authenticated %}
{% if applications %}
<div class="container w3-main">
    <h3>{{title}}</h3>
    {% for application in applications %}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
            {% if application.picture %}
                <img alt="avatar" class="card-img" src="{{ application.picture.url }}" />
            {% else %}
                <img alt="avatar" class="card-img" src="{% static 'images/avatar.jpg' %}" />
            {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{ application.name }} {{ application.surname }}</h5>
            <p class="desc">{{ application.job_offer.title }}</p>
            <p class="card-text"><span class="desc"><i class="glyphicon glyphicon-calendar"></i> Sent: {{ application.created_date }}</span></small></p>
            <div class="info-bottom-area">
                <span class="info-btn"><a class="btn btn-lg btn-primary" href="{% url 'jobs:application_detail' application.id %}" role="button">View Application</a></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
      </div>
    </div>
{% endfor %}

      
    {% else %}
    <div class="w3-margin container" style="padding-left: 20%">
    <h1>There are no applications.</h1>
  </div>
{% endif %}
{% else %}
<div class="container w3-margin">
    <h1>You're not logged in.</h1>
    <a href="{% url 'login' %}">Login</a>
  </div>
{% endif %}
{% endblock %} 
  </div>
        </div>
      </div>

    </div>
</div>

</html>

users/templates/users/login.html
<html>
	<head>
		<title>Log In</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</head>
	{% extends 'users/navbar.html' %}
{% block body %}
	<body>
		{% load crispy_forms_tags %}
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Log In</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Need an account?<a class="ml-2" href="{% url 'register' %}">Sign Up</a></small>
		</div>
	</div>
	</body>
	{% endblock %}
</html>

users/templates/users/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  			<!-- Navbar content -->
  			<a class="navbar-brand" href="{% url 'homepage' %}">Forum-Mind</a>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'homepage' %}">Home</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'news' %}"><span class="sr-only"></span>TechNews</a>
			      </li>
  			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'jobs:index' %}">Job Portal</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="/forums/">Q&A Forum</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="/community/">Community</a>
			      </li>
			    </ul>
			</div>
			    <div class="navbar-nav">
			    	{% if user.is_authenticated %}
			    	<a class="nav-item nav-link" href="{% url 'profile' %}">Hello {{user.username}}</a>
			    	<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
			    	{% else %}
			    	<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
			    	<a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
			    	{% endif %}
			    </div>
		</nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{message.tags}}">
					{{message}}
				</div>
			{% endfor %}
		{%endif%}
{% block body %}
{% endblock %}

users/templates/users/user_conversations.html
<html>
    <head>
        <title>Forum-Mind Profile </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href='https://fonts.googleapis.com/css?family=RobotoDraft' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><style>
    html,body,h1,h2,h3,h4,h5 {font-family: "RobotoDraft", "Roboto", sans-serif;}
    .w3-bar-block .w3-bar-item{padding:16px}
    </style>
    </head>
{% extends 'hub/navbar.html' %}
{% block body %}

<nav class="w3-sidebar w3-bar-block w3-collapse w3-white w3-animate-left w3-card" style="z-index:3;width:320px;" id="mySidebar">
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-border-bottom w3-large"><h2><b>Forum-Mind</b></h2></a>
  <a href="javascript:void(0)" onclick="w3_close()" title="Close Sidemenu" 
  class="w3-bar-item w3-button w3-hide-large w3-large">Close <i class="fa fa-remove"></i></a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button" ><i class="fa fa-star"></i> My Profile</a>
  <a href="{% url 'profacc' %}" class="w3-bar-item w3-button"><i class="fa fa-trophy"></i> My Accomplishments</a>
  <a href="/profile/github/{{user.username}}" class="w3-bar-item w3-button"><i class="fa fa-github-alt"></i>
  </i> Github Activity</a>
  <a href="{% url 'profile-edit' %}" class="w3-bar-item w3-button"><i class="fa fa-pencil"></i> Edit Profile</a>
  
  <a href="{% url 'applications' %}" class="w3-bar-item w3-button"><i class="fa fa-hourglass-end w3-margin-right"></i>My Applications</a>
  <a href="{% url 'joboffers' %}" class="w3-bar-item w3-button"><i class="fa fa-paper-plane w3-margin-right"></i>My Offers</a>
  <a href="{% url 'jobcandidates' %}" class="w3-bar-item w3-button"><i class="fa fa-user w3-margin-right"></i>
Candidates</a>
  <a href="{% url 'jobconv' %}" class="w3-bar-item w3-button" style="background-color:#D3D3D3"><i class="fa fa-envelope w3-margin-right"></i>
Messages</a>
</nav>


<!-- Overlay effect when opening the side navigation on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="Close Sidemenu" id="myOverlay"></div>

<script>

  function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
  }

  function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
  }
</script>

<script>
  var openTab = document.getElementById("firstTab");
  openTab.click();
</script>



<!-- Page content -->
<br/><br/><p></p>
<div class="container w3-main">
{% if conversations %}
  <h3><b>Conversations:</b></h3><br/>
  {% if request.user.is_authenticated %}
  {% for conversation in conversations %}
  <ul class="w3-ul w3-card-4" style="width:50%">
    <li class="w3-bar">
      <a href="{% url 'jobs:conversation_delete' conversation.id %}"><span class="w3-bar-item w3-button w3-xlarge w3-right">&times;</span></a>
      <div class="w3-bar-item">
        <a href="{% url 'jobs:conversation' conversation.id %}">
          {{ conversation.title }} - <i>{{conversation.user_two}}</i>
        </a>
      </div><br/>
    </li>
  </ul>
  <br/>
  {% endfor %}
{% else %}
    <h1>You're not logged in.</h1>
      <a href="{% url 'auth_login' %}">Login</a>
{% endif %}
{% else %}
  <h3>No messages.</h3>
{% endif %}
</div>
{% endblock %}
</html>