Forum-Mind/urls.py
#Import Dependencies
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url,include
from users import views as user_views
from django.conf.urls.static import static
from users import views as user_views
from django.conf import settings

#URL Patterns
urlpatterns = [
	#/admin/
    path('admin/', admin.site.urls),
    #/
    path('',include('homepage.urls'),name='home'),
    #/news/
    path('news/',include('news.urls'),name='news'),
    #/jobs/
    path('jobs/',include('jobs.urls'),name='job'),
    #/forums/
    path('forums/',include('forums.urls'),name='forum'),
    #/community/
    path('community/',include('hub.urls'),name='community'),
    #/register/
    path('register/',user_views.register,name='register'),
    #/login/
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    #/logout/
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    #/profile/
    path('profile/',user_views.profile,name='profile'),
    #/profile/accomplishments/
    path('profile/accomplishments/',user_views.accomplishments,name='profacc'),
    #/profile/edit/
    path('profile/edit/',user_views.edit,name='profile-edit'),
    #/profile/applications/
    path('profile/applications/',user_views.applications,name='applications'),
    #/profile/offers/
    path('profile/offers/',user_views.offers,name='joboffers'),
    #/profile/candidates/
    path('profile/candidates/',user_views.candidates,name='jobcandidates'),
    #/profile/converstaions/
    path('profile/converstaions/',user_views.user_conversations,name='jobconv'),
    #/profile/github/<username>/
    path('profile/github/<str:username>',user_views.github,name='profgit'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hub/urls.py
#Import Dependencies
from django.urls import path
from django.conf.urls import url,include
from . import views
from .views import (
	PostListView,
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserPostListView
	)

#URL Patterns
urlpatterns = [
	#/community/
	path('',PostListView.as_view(),name='network'),
	#/community/new/
	path('new/',PostCreateView.as_view(),name='network-create'),
	#/community/<pk>
	path('<int:pk>/',PostDetailView.as_view(),name='network-post'),
	#/community/<pk>/update/
	path('<int:pk>/update/',PostUpdateView.as_view(),name='network-update'),
	#/community/<pk>/delete/
	path('<int:pk>/delete/',PostDeleteView.as_view(),name='network-delete'),
	#/community/user/<username>
	path('user/<str:username>',UserPostListView.as_view(),name='user-posts'),	
]

jobs/urls.py
#Import Dependencies
from django.conf.urls import url
from . import views

#App Name
app_name = 'jobs'

#URL Patterns
urlpatterns = [
    #/jobs/
    url(r'^$', views.index, name='index'),

    #/jobs/offers/
    url(r'^offers/$', views.job_offers, name='job_offers'),

    #/jobs/offers/<offerid>/
    url(r'offers/(?P<offer_id>[0-9]+)/$', views.offer_detail, name='offer_detail'),    

    #/jobs/offers/<offer_id>/apply/
    url(r'offers/(?P<offer_id>[0-9]+)/apply/$', views.job_apply, name='job_apply'),

    #/jobs/offers/<offerid>/add/
    url(r'offers/add/$', views.job_offer_add, name='job_offer_add'),    

    #/jobs/offers/<id>/delete/
    url(r'offers/(?P<offer_id>[0-9]+)/delete/$', views.offer_delete, name='offer_delete'),

    #/jobs/offers/update/
    url(r'offers/(?P<offer_id>[0-9]+)/update/$', views.offer_update, name='offer_update'),

    #/jobs/applications/<id>
    url(r'applications/(?P<application_id>[0-9]+)/$', views.application_detail, name='application_detail'),

    #/jobs/applications/<id>/create_conversation/
    url(r'applications/(?P<application_id>[0-9]+)/create_conversation/$', views.create_conversation, name='create_conversation'),

    #/jobs/search/
    url(r'search/$', views.search, name='search'),
    
    #/jobs/messages/<id>/delete/
    url(r'^messages/(?P<conversation_id>[0-9]+)/delete$', views.conversation_delete, name='conversation_delete'),
    
    #/jobs/messages/<id>/
    url(r'^messages/(?P<conversation_id>[0-9]+)/$', views.conversation, name='conversation'),
    
    #/jobs/users/<name>/
    url(r'^users/(?P<username>\w+)/$', views.user_profile, name='user_profile'),

    #/jobs/users/<name>/applications/
    url(r'^users/(?P<username>\w+)/applications', views.user_applications, name='user_applications'),
    
    #/jobs/users/<name>/offers/
    url(r'^users/(?P<username>\w+)/offers', views.user_offers, name='user_offers'),

    #/jobs/users/<name>/candidates/
    url(r'^users/(?P<username>\w+)/candidates', views.candidates, name='candidates'),       

    #/jobs/users/<name>/conversations/
    url(r'^users/(?P<username>\w+)/conversations/$', views.user_conversations, name='user_conversations'),
]

jobs/views.py
#Import Dependencies
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth.decorators import login_required

#Views
# Home Page
def index(request):
    return render(request, 'jobs/index.html', {})

#Post Message
@login_required
def post_message(request, conversation_id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            messageForm = MessageForm(request.POST)
            conversation = get_object_or_404(Conversation, id=conversation_id)
            if messageForm.is_valid() \
                    and (conversation.user_one == request.user or conversation.user_two == request.user):
                message = messageForm.save(commit=False)
                message.user = request.user
                message.conversation = conversation
                message.content = request.POST.get('content')
                message.save()

        return redirect('jobs:conversation', conversation_id=conversation_id)

    return redirect('auth_login')

# Create Conversation
@login_required
def create_conversation(request, application_id):
    if request.user.is_authenticated:
        application = get_object_or_404(JobApplication, id=application_id)
        if request.user == application.job_offer.user:
            conversationForm = ConversationForm()
            conversation = conversationForm.save(commit=False)
            conversation.user_one = request.user
            conversation.user_two = application.user
            conversation.title = application.job_offer.title
            conversation.save()

            return redirect('jobs:conversation', conversation_id=conversation.id)

    return redirect('auth_login')

# Conversation
@login_required
def conversation(request, conversation_id):
    if request.method == 'POST':
        return post_message(request, conversation_id)

    if request.user.is_authenticated:
        conversation = get_object_or_404(Conversation, id=conversation_id)
        if conversation.user_one == request.user or conversation.user_two == request.user:
            conversations = Conversation.objects.filter(
                Q(user_one=request.user) |
                Q(user_two=request.user)
            )
            messages = Message.objects.filter(conversation_id=conversation.id)
            paginator = Paginator(messages, 10)
            page = request.GET.get('page')

            try:
                messages = paginator.page(page)
            except PageNotAnInteger:
                messages = paginator.page(1)
            except EmptyPage:
                messages = paginator.page(paginator.num_pages)

            context = {
                'messages': messages,
                'conversation': conversation,
                'conversations': conversations,
            }
            return render(request, 'jobs/conversation.html', context)

    return redirect('auth_login')


# Delete Conversation
@login_required
def conversation_delete(request, conversation_id):
    if request.user.is_authenticated:
        conversation = get_object_or_404(Conversation, id=conversation_id)
        if conversation.user_one == request.user or conversation.user_two == request.user:
            conversation.delete()
            return redirect('jobs:user_conversations', username=request.user.username)

    return redirect('auth_login')


# User Conversations
@login_required
def user_conversations(request, username):
    if request.user.is_authenticated:
        conversations = Conversation.objects.filter(
            Q(user_one=request.user) |
            Q(user_two=request.user)
        )
        context = {
            'conversations': conversations,
        }
        return render(request, 'jobs/user_conversations.html', context)


# Search
def search(request):
    offers = None
    title = 'Search for: '
    if (('title' in request.GET) and request.GET['title'].strip()) \
            or (('location' in request.GET) and request.GET['location'].strip()) \
            or (('industry' in request.GET) and request.GET['industry'].strip()):

        queryTitle = request.GET['title']
        queryLocation = request.GET['location']
        queryIndustry = request.GET['industry']
        title += queryTitle + ' ' + queryLocation + ' ' + queryIndustry

        offers = JobOffer.objects.filter(
            Q(title__icontains=queryTitle) &
            Q(location__icontains=queryLocation) &
            Q(industry__icontains=queryIndustry)
        )

    industries = JobOffer.INDUSTRY_TYPES
    context = {
        'title': title,
        'offers': offers,
        'industries': industries,
    }
    return render(request, 'jobs/offers.html', context)


# User Profile
@login_required
def user_profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'jobs/user_profile.html', {'user': user})


# Application Details
@login_required
def application_detail(request, application_id):
    application = get_object_or_404(JobApplication, id=application_id)
    if request.user.is_authenticated and \
            (application.job_offer.user == request.user or application.user == request.user):
        languages = None
        if application.languages:
            languages = application.languages.rstrip().split('-')
            #print(languages)
            languages =  filter(None, languages)
        context = {
            'languages': languages,
            'application': application,
        }
        return render(request, 'jobs/application_detail.html', context)

    return redirect('jobs:index')


# Delete Offer
@login_required
def offer_delete(request, offer_id):
    offer = get_object_or_404(JobOffer, id=offer_id)
    if request.user.is_authenticated and offer.user == request.user:
        offer.delete()
        return redirect('/jobs/offers/', username=request.user.username)

    return redirect('jobs:index')

# Update Offer
@login_required
def offer_update(request, offer_id):
    title = ''
    offer = get_object_or_404(JobOffer, id=offer_id)
    requirements = get_object_or_404(ApplicationRequirements, job_offer__id=offer_id)

    if request.user.is_authenticated and offer.user == request.user:
        offerForm = JobOfferForm(request.POST or None, instance=offer)
        requirementsForm = ApplicationForm(request.POST or None, instance=requirements)
        if request.method == 'POST':
            if offerForm.is_valid() and requirementsForm.is_valid():
                offerForm.save()
                requirementsForm.save()
                return redirect('jobs:offer_detail', offer_id=offer_id)
            else:
                title = 'Invalid Data while updating fields.'

        context = {
            'offerForm': offerForm,
            'title': title,
            'requirements': requirementsForm,
        }
        return render(request, 'jobs/job_offer_add.html', context)

    return redirect('jobs:index')


# User Applications
@login_required
def user_applications(request, username):
    applications = []
    title = 'Your Applications'
    if request.user.is_authenticated:
        applications = JobApplication.objects.filter(user=request.user).order_by('-created_date')

    paginator = Paginator(applications, 10)
    page = request.GET.get('page')

    try:
        applications = paginator.page(page)
    except PageNotAnInteger:
        applications = paginator.page(1)
    except EmptyPage:
        applications = paginator.page(paginator.num_pages)

    context = {
        'applications': applications,
        'title': title,
    }
    return render(request, 'jobs/user_applications.html', context)


# Candidates
@login_required
def candidates(request, username):
    applications = []
    title = 'Your Candidates'
    if request.user.is_authenticated:
        applications = JobApplication.objects.filter(job_offer__user=request.user).order_by('-created_date')

    paginator = Paginator(applications, 10)
    page = request.GET.get('page')

    try:
        applications = paginator.page(page)
    except PageNotAnInteger:
        applications = paginator.page(1)
    except EmptyPage:
        applications = paginator.page(paginator.num_pages)

    context = {
        'applications': applications,
        'title': title,
    }
    return render(request, 'jobs/candidates.html', context)


# User Offers
@login_required
def user_offers(request, username):
    offers = []
    if request.user.is_authenticated:
        offers = JobOffer.objects.filter(user=request.user).order_by('-created_date')
        paginator = Paginator(offers, 10)
        page = request.GET.get('page')

        try:
            offers = paginator.page(page)
        except PageNotAnInteger:
            offers = paginator.page(1)
        except EmptyPage:
            offers = paginator.page(paginator.num_pages)

    return render(request, 'jobs/user_offers.html', {'offers': offers})

# Job Offers
def job_offers(request):
    offers = JobOffer.objects.all().order_by('-created_date')
    industries = JobOffer.INDUSTRY_TYPES
    paginator = Paginator(offers, 10)
    page = request.GET.get('page')

    try:
        offers = paginator.page(page)
    except PageNotAnInteger:
        offers = paginator.page(1)
    except EmptyPage:
        offers = paginator.page(paginator.num_pages)

    context = {
        'offers': offers,
        'industries': industries,
    }
    return render(request, 'jobs/offers.html', context)


# Add Job Offers
@login_required
def job_offer_add(request):
    title = ""
    if request.method == 'POST':
        offerForm = JobOfferForm(request.POST, request.FILES)
        requirementsForm = ApplicationForm(request.POST)
        if offerForm.is_valid() and requirementsForm.is_valid():
            job_offer = offerForm.save(commit=False)
            job_offer.user = request.user

jobs/templates/jobs/application_detail.html
<html>
    <head>
        <title>Application</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href='https://fonts.googleapis.com/css?family=RobotoDraft' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><style>
    html,body,h1,h2,h3,h4,h5 {font-family: "RobotoDraft", "Roboto", sans-serif;}
    .w3-bar-block .w3-bar-item{padding:16px}
    </style>
    </head>
{% extends 'hub/navbar.html' %}
{% load static %}
{% block body %}

<nav class="w3-sidebar w3-bar-block w3-collapse w3-white w3-animate-left w3-card" style="z-index:3;width:320px;" id="mySidebar">
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-border-bottom w3-large"><h2><b>Forum-Mind</b></h2></a>
  <a href="javascript:void(0)" onclick="w3_close()" title="Close Sidemenu" 
  class="w3-bar-item w3-button w3-hide-large w3-large">Close <i class="fa fa-remove"></i></a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-star"></i> My Profile</a>
  <a href="{% url 'profacc' %}" class="w3-bar-item w3-button"><i class="fa fa-trophy"></i> My Accomplishments</a>
  <a href="{% url 'profile-edit' %}" class="w3-bar-item w3-button"><i class="fa fa-pencil"></i> Edit Profile</a>
  
  <a href="{% url 'applications' %}" class="w3-bar-item w3-button"><i class="fa fa-hourglass-end w3-margin-right"></i>My Applications</a>
  <a href="{% url 'joboffers' %}" class="w3-bar-item w3-button"><i class="fa fa-paper-plane w3-margin-right"></i>My Offers</a>
  <a href="{% url 'jobcandidates' %}" class="w3-bar-item w3-button"  style="background-color:#D3D3D3"><i class="fa fa-user w3-margin-right"></i>
Candidates</a>
  <a href="{% url 'jobconv' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope w3-margin-right"></i>
Messages</a>
</nav>


<!-- Overlay effect when opening the side navigation on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="Close Sidemenu" id="myOverlay"></div>

<script>

  function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
  }

  function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
  }
</script>

<script>
  var openTab = document.getElementById("firstTab");
  openTab.click();
</script>



<!-- Page content -->
<br/><br/><p></p>
{% if applications %}
    <div class="row">
        <div class="col-sm-8 col-lg-9" style="text-align: center;">
            <div class="pagination">
                <span class="step-links">
                    {% if applications.has_previous %}
                    <a href="?page={{ applications.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ applications.number }} of {{ applications.paginator.num_pages }}.
                    </span>

                    {% if applications.has_next %}
                        <a href="?page={{ applications.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endif %}
<br/><br/><p></p>

<div class="container w3-main">
    <div class="card mb-3" style="max-width: 100%;">
      <div class="row no-gutters">
        <div class="col-md-4">
            {% if application.picture %}
                <img alt="avatar" class="card-img" src="{{ application.picture.url }}" />
            {% else %}
                <img alt="avatar" class="card-img" src="{% static 'images/avatar.jpg' %}" />
            {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h1><strong>{{ application.name }} {{ application.surname }}</strong></h1>
            {% if application.age %}
              <p style="font-size: 18px;"><strong>Age: </strong> {{ application.age }}</p>
            {% endif %}
              <p style="font-size: 18px;"><strong>Email: </strong> {{ application.email }}</p>
            {% if application.education %}
              <p style="font-size: 18px;"><strong>Education: </strong> {{ application.education }}</p>
            {% endif %}
            {% if application.placeOfResidence %}
              <p style="font-size: 18px;"><strong>Location: </strong> {{ application.placeOfResidence }}</p>
            {% endif %}
            {% if application.currentStatus %}
              <p style="font-size: 18px;"><strong>Working Status: </strong> {{ application.currentStatus }}</p>
            {% endif %}
                {% if application.aboutYou %}
            <div class="row">
                <div class="col-md-12" style="padding-left: 1cm;">
                    <h2 >About Me:</h2>
                    <p>{{ application.aboutYou }}</p>
                </div>
            </div>
            <hr/>
            {% endif %}

            {% if application.experience %}
            <div class="row">
                <div class="col-md-12" style="padding-left: 1cm;">
                    <h2 >My Experience:</h2>
                    <p>{{ application.experience }}</p>
                </div>
            </div>
            <hr/>
            {% endif %}

            {% if languages %}
            <div class="row">
                <div style="padding-left: 1cm;">
                    <h2>Languages:</h2>
                    <ul>
                        {% for language in languages %}
                            <li>{{ language }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <hr/>
            {% endif %}

            {% if application.hobby %}
            <div class="row">
                <div class="col-md-12" style="padding-left: 1cm;">
                    <h2 >My Hobby:</h2>
                    <p>{{ application.hobby }}</p>
                </div>
            </div>
            <hr/>
            {% endif %}
        </div>
        {% if application.job_offer.user == request.user %}
        <div class="info-bottom-area">
            <div class="title col-md-4 col-sm-offset-4">
                <a class="btn btn-lg btn-primary" href="{% url 'jobs:create_conversation' application.id %}" role="button">Contact</a>
            </div>
        </div>
        {% endif %}

        <div>
            <br><br><br>
        </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
  </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}
</html>

jobs/templates/jobs/offer_detail.html
{% extends 'jobs/base.html' %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="/static/css/offer_detail.css">
{% endblock %}


{% block content %}

<div class="offer col-md-8 col-sm-offset-2">
    <div class="row">
        <div class="offer_image col-md-12 title">
            <a> <img src="{{ offer.avatar.url }}"> </a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            {% for about in aboutUs %}
            <p class="title">{{ about }}</p>
            {% endfor %}
        </div>

    </div>
    <br>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 class="title">{{ offer.title }}</h1>
            <div class="location">
                <p><i class="fa fa-location-arrow" aria-hidden="true"></i> Location: {{ offer.location }}</p>
                {% if offer.salary %}
                    <p><i class="fa fa-money" aria-hidden="true"></i>  Salary: {{ offer.salary }}$</p>
                {% endif %}
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="custom-list">
            <p><strong>Requirements:</strong></p>
            <ul>
                {% for requirement in requirements %}
                    <li>{{ requirement }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="custom-list">
            <p><strong>Job Description:</strong></p>
            <ul>
                {% for job in jobDescription %}
                    <li>{{ job }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="custom-list">
            <p><strong>We Offer:</strong></p>
            <ul>
                {% for weOffer in whatWeOffer %}
                    <li>{{ weOffer }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <br><br><br>
</div>

{% if request.user.is_authenticated and request.user != offer.user %}

    <div class="row">
        <div class="title col-md-4 col-sm-offset-4">
            <a class="btn btn-lg btn-primary" href="{% url 'jobs:job_apply' offer.id %}" role="button">Apply Now!</a>
        </div>
    </div>

{% elif request.user == offer.user %}

    <div class="row">
        <div class="title col-md-4 col-sm-offset-4">
            <a class="btn btn-lg btn-primary" href="{% url 'jobs:offer_update' offer.id %}" role="button">Edit</a>
            <a class="btn btn-lg btn-danger" href="{% url 'jobs:offer_delete' offer.id %}" role="button">Delete</a>
        </div>
    </div>

{% else %}

{% endif %}

<br><br><br>

{% endblock %}

jobs/templates/jobs/offers.html
{% extends 'jobs/base.html' %}

{% block style %}

    a {
        color: #222222;
    }

    .custom-input
    {
        width: 90%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    .custom-select
    {
        width: 90%;
        margin-left: auto;
        margin-right: auto;
    }

    .custom-button
    {
        width: 90%;
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-4 col-lg-3">
          <nav class="navbar navbar-default navbar-fixed-side" style="text-align: center;">
              <br>
            <form role="search" method="get" action="{% url 'jobs:search' %}">
                <label for="ftitle">Job Title</label>
                <input class="custom-input" type="text" id="ftitle" name="title" value="{{ request.GET.title }}" placeholder="title"><br>
                <label for="flocation">Location</label>
                <input class="custom-input" type="text" id="flocation" name="location" value="{{ request.GET.location }}" placeholder="location"><br>
                <label for="industry">Industry</label>
                <select class="form-control custom-select" id="industry" name="industry">
                        <option></option>
                    {% for industry in industries %}
                        <option value="{{ industry.0 }}">{{ industry.0 }}</option>
                    {% endfor %}
                </select>
              <input class="custom-button" type="submit" value="Search">
            </form>
              <hr/>
              <p style="color: #3B5998;">Looking for an Employee?</p>
              {% if request.user.is_authenticated %}
                <a class="btn btn-lg btn-primary" href="{% url 'jobs:job_offer_add' %}" role="button">Add Offer</a>
              {% else %}
                <p style="color: #3B5998;">Join Us!</p>
                <a href="{% url 'register' %}">Register</a>
              {% endif %}
          </nav>
        </div>

        <div class="col-sm-8 col-lg-9" style="text-align: center;">

            {% if offers %}
                <h1>All Job Offers</h1>
                <p>{{ title }}</p>
                <br>
                <ul class="event-list">
                    {% for offer in offers %}
                        <li>
                            <img alt="avatar" src="{{ offer.avatar.url }}" />
                            <div class="info">
                                <h2 class="title"><a href="{% url 'jobs:offer_detail' offer.id %}">{{ offer.title }}</a></h2>
                                <br>
                                <p class="desc">{{ offer.companyName }}</p>
                                <br>
                                <span class="desc"><i class="glyphicon glyphicon-calendar"></i> Added: {{ offer.created_date }}</span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <h1>There is no offers in database</h1>
            {% endif %}
        </div>
    </div>

{% if offers %}
    <div class="row">
        <div class="col-sm-4 col-lg-3">
        </div>
        <div class="col-sm-8 col-lg-9" style="text-align: center;">
            <div class="pagination">
                <span class="step-links">
                    {% if offers.has_previous %}
                    <a href="?page={{ offers.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ offers.number }} of {{ offers.paginator.num_pages }}.
                    </span>

                    {% if offers.has_next %}
                        <a href="?page={{ offers.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

jobs/templates/jobs/user_profile.html
{% extends 'jobs/base.html' %}

{% block style %}
{{ block.super }}

{% endblock %}


{% block content %}

<div class="container">
{% if request.user.is_authenticated %}
  <div class="row">
    <div class="col-sm-4 col-lg-3">
      <nav class="navbar navbar-default navbar-fixed-side" style="text-align: center;">
          <p><a href="{% url 'jobs:user_applications' request.user.username %}">Your Applications</a></p>
          <p><a href="{% url 'jobs:user_offers' request.user.username %}">Your Offers</a></p>
          <p><a href="{% url 'jobs:candidates' request.user.username %}">Your Candidates</a></p>
          <p><a href="{% url 'jobs:user_conversations' request.user.username %}">Messages</a></p>
      </nav>
    </div>
    <div class="col-sm-8 col-lg-9" style="text-align: center;">
        {% block user_view %}

        {% endblock %}
    </div>
  </div>
{% else %}
    <h1>You're not logged in.</h1>
      <a href="{% url 'login' %}">Login</a>
{% endif %}
</div>

{% endblock %}